login:
    path:     /login
    defaults: { _controller: RajkaranPortfolioBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

admin:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/home
        permanent: true

admin_home:
    path: /admin/home
    defaults: {_controller: RajkaranPortfolioBundle:BackEnd:home }

admin_career_timeline:
    path: /admin/careerTimeline
    defaults: {_controller: RajkaranPortfolioBundle:BackEnd:careerTimeline }

project:
    path:      /admin/careerTimeline/{project}
    defaults:  { _controller: RajkaranPortfolioBundle:BackEnd:project }

admin_about_me:
    path: /admin/aboutMe
    defaults: {_controller: RajkaranPortfolioBundle:BackEnd:aboutMe }



home:
    path: /
    defaults: {_controller: RajkaranPortfolioBundle:FrontEnd:home }

fe_project:
    path:      /careerTimeline/{project}
    defaults:  { _controller: RajkaranPortfolioBundle:FrontEnd:project }

fe_enquiry:
    path:      /enquiry
    defaults:  { _controller: RajkaranPortfolioBundle:FrontEnd:enquiryEmail }
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
