services:
    helper:
        class:       Rajkaran\PortfolioBundle\Services\HelperService
        arguments:   ['@doctrine']

    timeline:
        class:       Rajkaran\PortfolioBundle\Services\CareerTimelineService
        arguments:   ['@doctrine', '@helper']
