<?php

namespace Rajkaran\PortfolioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CareerTimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareerTimelineRepository extends EntityRepository
{
	public function findAllProjects(){
		return $this->getEntityManager()
            ->createQuery( 'SELECT h FROM RajkaranPortfolioBundle:CareerTimeline h ORDER BY h.developedWhen DESC' )
            ->getResult();
	}
	
	public function findProjectByName($project){
		return $this->getEntityManager()
            ->createQuery( 'SELECT h FROM RajkaranPortfolioBundle:CareerTimeline h WHERE h.projectName=:name' )
			->setParameter('name', $project)
            ->getResult();
	}
	
}
